GET http://localhost:3001/prueba HTTP/1.1
###

POST http://localhost:3001/signup 
Content-Type: application/json

{
    "name": "nacho",
    "country": "Argentina",
    "email": "nacho@gmail.com",
    "institution":"Henry",
    "password": "nacho"

}
###
POST http://localhost:3001/signin 
Content-Type: application/json

{
    
    "email": "pepe@gmail.com",
    "password": "pepe"

}
###
POST http://localhost:3001/islog 
Content-Type: application/json

{ 
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWVkZWU2M2E4MGYwMTNiMzg3NmRmNSIsImlhdCI6MTYzNzgwMjk3NX0.3WxjldnWv1VuNJSQaXzcyz5m4Mm30hhhAcQ1XGno5YU"
}
###
POST http://localhost:3001/Institution 
Content-Type: application/json

{
    "name": "Henryyyyy"
}