GET https://rocketproject2021.herokuapp.com/getProfiles HTTP/1.1
###

POST https://rocketproject2021.herokuapp.com/signup 
Content-Type: application/json

{
    "name": "nacho Perez",
    "country": "Argentina",
    "email": "nacho@gmail.com",
    "institution":"Nacho",
    "password": "nacho"

}
###
POST https://rocketproject2021.herokuapp.com/signin 
Content-Type: application/json

{
    
    "email": "pepe@gmail.com",
    "password": "pepe"

}
###
POST https://rocketproject2021.herokuapp.com/islog 
Content-Type: application/json

{ 
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWVkZWU2M2E4MGYwMTNiMzg3NmRmNSIsImlhdCI6MTYzNzgwMjk3NX0.3WxjldnWv1VuNJSQaXzcyz5m4Mm30hhhAcQ1XGno5YU"
}
###
POST https://rocketproject2021.herokuapp.com/Institution 
Content-Type: application/json

{
    "name": "Henryyyyy"
}
###
POST https://rocketproject2021.herokuapp.com/filterUserByTable
Content-Type: application/json
{
table: 1
}
